### ISSUE TITLE
Generate basic requirements (optional)

### ISSUE THREAD

**Issue by jerome3o** [vahfanforever/website#1]
Just some thoughts on what you want your site to do / be like.

This is an optional task, I just usually find it useful to think about these things when planning / working on a project.

Make a list of things your site needs to do, you can post it back here (on this issue) or add it to your project docs in the README or similar

Some things you might need to consider:
* How important are aesthetics?
* How much data do you want to display?
* How often will the data be updated?
* How much work are you ok with doing per data update?
    * can it be automated?
* How complicated do you want it to be? i.e. do you want it to just be statically served (with manual data updates to source code) or should it have a database that can be managed outside of source code?
* Is this for learning, or is the output more important? (or both, and in what proportion)

**Comment by vahfanforever** [comment]
Want this website to be kind of like a resume -- would be cool to have like a section for her basketball stats but then can put other stuff on here like her creative portfolio. Also would like to have her highlight reels on here as well.

**How important are aesthetics?**
- High priority -- I don't want to be associated to this website if it's not something I think is cute/nice to look at

**How much data do you want to display?**
- Maybe start with some basic stats like points per game, rebounds per game, assists per game and maybe minutes per game.
-  Eventually want to put some cool plots/stats on there that utilises the whole games data like when she's on the court vs. off the court how effective is her team

**How often will the data be updated?**
- Once a week

**How much work are you ok with doing per data update?**
- I'm okay with manually updating the data

**Can it be automated?**
- Probably -- they'll post up stats after a game on their website

**How complicated do you want it to be? i.e. do you want it to just be statically served (with manual data updates to source code) or should it have a database that can be managed outside of source code?**
- Maybe manual data updates to the source code keeping in mind that I might want to have a database later


**Is this for learning, or is the output more important? (or both, and in what proportion)**
- Output is more important -- 60/40

**Comment by jerome3o** [comment]
Okay sweet that's good to know!

Given that aesthetics is a priority I think you should spend a good amount of time reading up on some CSS/HTML and finding some nice templates to start from. This site looks ok https://webflow.com/free-website-templates but have a gander around. (I'm defs not a pro at making websites look pretty haha)
